### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by chrisjd20** [Devollin/Omnitween#2]
Would love to give this a shot but documentation/examples are non existent.

**Comment by Devollin** [comment]
I apologize for taking so long to add documentation; it's been added. 
In case it wasn't clear before, this project is far from complete, and is lacking in many of the features I listed on the README; I want to get to them eventually, but I'll have to redo the current system before I add them.

**Comment by chrisjd20** [comment]
OK perfect thanks for the update. I got to poking around at it and I'm really liking it. Thanks!
